imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:  "pdo_sqlite"
        path:    "%kernel.cache_dir%/db.sqlite"
        charset: "UTF8"
#    dbal:
#        driver:   pdo_mysql
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
#        # if using pdo_sqlite as your database driver:
#        #   1. add the path in parameters.yml
#        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
#        #   2. Uncomment database_path in parameters.yml.dist
#        #   3. Uncomment next line:
#        #     path:     "%database_path%"
#
#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
